### ISSUE TITLE
ModuleNotFoundError: No module named 'swinfir.metrics'

### ISSUE THREAD

**Issue by imkelt** [Zdafeng/SwinFIR#2]
ModuleNotFoundError: No module named 'swinfir.metrics'

**Comment by selfish0618** [comment]
> ModuleNotFoundError: No module named 'swinfir.metrics'

you can add '#' before 'import swinfir.metrics' in the file.

**Comment by maxpolaczuk** [comment]
I deleted `from .metrics import *` from the `__init__.py` and it seems to work when running inference
