### ISSUE TITLE
Pretrained weights on ImageNet only

### ISSUE THREAD

**Issue by PhuTran1005** [Zdafeng/SwinFIR#8]
Thank you for your great work.

Can you provide the pre-trained model on ImageNet only that is used for fine-tuning DF2K datasets?
Thanks.

**Comment by Zdafeng** [comment]
I'm sorry, I deleted SwinFIR's pre-trained model on ImageNet, but I saved HATFIR's pre-trained model. You can find them here https://drive.google.com/drive/folders/1wiJcFJA4DxIISB7b_qz4u-kA1WE6EJOk.
